language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t arfiz/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true arfiz/docker-react npm run test